### ISSUE TITLE
rails error in response text of grader api calls

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#561]
I got this 
```
 u'{"message":"undefined method `deep_merge\' for \\"file_key\\":String","submission_id":"4402","submissions_remaining":10,"reset_date":"2018-03-02T14:58:09.519Z"}
```
as a response for when trying to patch a submission.

**Comment by scarroll32** [comment]
I'll need the call details and the headers if possible.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdAI-KIT-energy-challenge-job-factory/blob/master/workers.py#L65

**Comment by scarroll32** [comment]
Step 1: make a post request with status submitted
Step 2: collect the submission id from the reaponse from step 1
Step 3: make a patch request with a new payload and grading status failed, and also add a random meta key to the payload

**Comment by scarroll32** [comment]
Fixed

**Comment by spMohanty** [comment]
I still see this error when I patch a submission with a meta key in it.

**Comment by scarroll32** [comment]
Is this fixed now? @spMohanty

**Comment by spMohanty** [comment]
Yes
