### ISSUE TITLE
Remove button in challenge edit not working

### ISSUE THREAD

**Issue by englhardt** [crowdAI/crowdai#777]
The remove button when editing a challenge is not working in two places.

1. Submission File Definition
![screenshot_2018-05-09_09-31-27](https://user-images.githubusercontent.com/7440669/39801629-1cf9464a-536c-11e8-9702-a7d50bc4f61b.png)

2. Invited participant
![screenshot_2018-05-09_09-32-42](https://user-images.githubusercontent.com/7440669/39801649-2a169aee-536c-11e8-82a5-f05a51623b71.png)

This is due to cocoon no knowing what to remove ([doc](https://github.com/nathanvda/cocoon#link_to_remove_association)).

Fixes

1. The table is generated [here](https://github.com/crowdAI/crowdai/blob/master/app/views/challenges/form/_invitations_table.html.erb#L12). The class `nested-fields` is missing for the objects. The fix would probably require to extract the list generation into a partial? I am not sure how to handle this.
2. One can easily add the missing class `nested-fields` [here](https://github.com/crowdAI/crowdai/blob/master/app/views/challenges/form/_submission_file_definition_fields.html.erb#L1).

**Comment by scarroll32** [comment]
Thanks for this report @englhardt . The issue for the table is fixed in dev and will soon be deployed. The submission file definitions will be refactored out completely, so it won't be fixed.

**Comment by scarroll32** [comment]
Implemented

**Comment by englhardt** [comment]
Unfortunately this is not fixed for point number 2 (participants of private challenge). Two problems occur now:
a) When clicken the remove button, all participants in the list are removed. The class `nested-fields` must probably be set in the `<tr>` of each row instead of in the `<tbody>`.
b) When updating the challenge after removing somebody, it is not saved. I.e., the participant is still in the list after reentering the challenge edit view.

**Comment by Sylvain-Bernard** [comment]
Seems that Invited participant issue (2) is still present

**Comment by scarroll32** [comment]
Implemented, thanks @farnir !
